import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext({ lang: "en", setLang: () => {} });

// All translations for the site
export const translations = {
  en: {
    switchOn: "Switch It On ⚡",
    watchVision: "Watch Vision Video",
    faithAlwaysOn: "⚡ Faith. Always On.",
    bibleVerse: '"You are the light of the world." — Matthew 5:14',
    heroSubtitle: "Join 1M+ young believers turning hidden faith into visible light — across the nations of the East-Central Africa Division.",
    heroTitle1: "Your Faith Is The",
    heroTitle2: "Switch",
    heroTitle3: "The World Is Waiting For",
    watchTitle: "Watch the",
    watchVisionText: "Vision",
    watchDesc: "Generation LightMode was born from a simple belief — that the world changes when young believers stop hiding their faith and start living it out loud. We are moving from hidden faith to visible light, transforming the digital landscape.",
    readMore: "Read More About the Vision →",
    lightSpreading: "The Light Is Spreading",
    realImpact: "Real impact. Real people. Real faith.",
    youthMobilized: "Youth to be Mobilized",
    peersReached: "Peers to be Reached",
    ecdNations: "ECD Nations",
    glowGroups: "GlowGroups Active",
    whatIsLightMode: "What Is",
    lightModeWord: "LightMode?",
    learnMore: "Learn More →",
    takePledge: "Take The",
    pledgeWord: "Pledge",
    signPledge: "Sign The Pledge ⚡",
    joinNow: "Join Now ⚡",
    glowRank: "Your Glow Rank",
    rankSubtitle: "Every step of faith levels you up. Where are you on the journey?",
    theMovement: "THE MOVEMENT",
    movementBadge: "The Movement Has Begun",
  },
  sw: {
    switchOn: "Washa Imani ⚡",
    watchVision: "Tazama Video ya Maono",
    faithAlwaysOn: "⚡ Imani. Daima Imewashwa.",
    bibleVerse: '"Ninyi ni nuru ya ulimwengu." — Mathayo 5:14',
    heroSubtitle: "Jiunge na vijana 1M+ wanaogeuza imani iliyofichwa kuwa nuru inayoonekana — katika mataifa ya Mgawanyiko wa Afrika ya Kati-Mashariki.",
    heroTitle1: "Imani Yako Ndiyo",
    heroTitle2: "Swichi",
    heroTitle3: "Ulimwengu Unangoja",
    watchTitle: "Tazama",
    watchVisionText: "Maono",
    watchDesc: "Generation LightMode ilizaliwa kutoka imani rahisi — kwamba ulimwengu hubadilika wakati vijana waaminifu wanacha kuficha imani yao na kuanza kuiishi hadharani.",
    readMore: "Soma Zaidi Kuhusu Maono →",
    lightSpreading: "Nuru Inaenea",
    realImpact: "Athari halisi. Watu halisi. Imani halisi.",
    youthMobilized: "Vijana wa Kuhamasishwa",
    peersReached: "Marafiki wa Kufikia",
    ecdNations: "Mataifa ya ECD",
    glowGroups: "GlowGroups Zinazofanya Kazi",
    whatIsLightMode: "LightMode ni",
    lightModeWord: "Nini?",
    learnMore: "Jifunza Zaidi →",
    takePledge: "Toa",
    pledgeWord: "Ahadi",
    signPledge: "Tia Sahihi Ahadi ⚡",
    joinNow: "Jiunge Sasa ⚡",
    glowRank: "Cheo Chako cha Nuru",
    rankSubtitle: "Kila hatua ya imani inakupandisha. Uko wapi safarini?",
    theMovement: "HARAKATI",
    movementBadge: "Harakati Imeanza",
  },
  fr: {
    switchOn: "Allume ta Foi ⚡",
    watchVision: "Voir la Vidéo Vision",
    faithAlwaysOn: "⚡ Foi. Toujours Allumée.",
    bibleVerse: '"Vous êtes la lumière du monde." — Matthieu 5:14',
    heroSubtitle: "Rejoignez plus d'1M de jeunes croyants transformant leur foi cachée en lumière visible — dans les nations de la Division Afrique du Centre-Est.",
    heroTitle1: "Ta Foi Est",
    heroTitle2: "L'Interrupteur",
    heroTitle3: "Que Le Monde Attend",
    watchTitle: "Regarder la",
    watchVisionText: "Vision",
    watchDesc: "Generation LightMode est née d'une croyance simple — que le monde change quand les jeunes croyants arrêtent de cacher leur foi.",
    readMore: "En Savoir Plus Sur la Vision →",
    lightSpreading: "La Lumière Se Répand",
    realImpact: "Impact réel. Personnes réelles. Foi réelle.",
    youthMobilized: "Jeunes à Mobiliser",
    peersReached: "Pairs à Atteindre",
    ecdNations: "Nations de l'ECD",
    glowGroups: "GlowGroups Actifs",
    whatIsLightMode: "Qu'est-ce que",
    lightModeWord: "LightMode?",
    learnMore: "En Savoir Plus →",
    takePledge: "Prendre",
    pledgeWord: "L'Engagement",
    signPledge: "Signer l'Engagement ⚡",
    joinNow: "Rejoindre Maintenant ⚡",
    glowRank: "Votre Rang Glow",
    rankSubtitle: "Chaque pas de foi vous élève. Où êtes-vous dans le voyage?",
    theMovement: "LE MOUVEMENT",
    movementBadge: "Le Mouvement a Commencé",
  },
  ln: {
    switchOn: "Tumbola Kondima ⚡",
    watchVision: "Tala Vidéo ya Makanisi",
    faithAlwaysOn: "⚡ Kondima. Ntango Nyonso Etumbolama.",
    bibleVerse: '"Bino bozali pole ya mokili." — Matai 5:14',
    heroSubtitle: "Kótá na bato ya kondima koleka 1M+ oyo bazali kobongola kondima oyo ebombamaki na pole ya komonana.",
    heroTitle1: "Kondima Na Yo Ezali",
    heroTitle2: "Swiche",
    heroTitle3: "Mokili Ezali Kosengela",
    watchTitle: "Tala",
    watchVisionText: "Makanisi",
    watchDesc: "Generation LightMode ebotamaki na ekaniseli ya pamba — ete mokili ebongwani ntango bilenge ya kondima basilisi kobomba kondima yango.",
    readMore: "Tanga Lisusu Mpo Na Makanisi →",
    lightSpreading: "Pole Ezali Kotambola",
    realImpact: "Ntina ya solo. Bato ya solo. Kondima ya solo.",
    youthMobilized: "Bilenge ya Kohamasishwa",
    peersReached: "Baninga ya Kokomela",
    ecdNations: "Bikolo ya ECD",
    glowGroups: "GlowGroups Oyo Ezali Kosala",
    whatIsLightMode: "LightMode Ezali",
    lightModeWord: "Nini?",
    learnMore: "Yekola Lisusu →",
    takePledge: "Pesa",
    pledgeWord: "Ndayi",
    signPledge: "Koma Ndayi ⚡",
    joinNow: "Kótá Sikoyo ⚡",
    glowRank: "Esika Na Yo ya Pole",
    rankSubtitle: "Libongo nyonso ya kondima elongi yo likoló. Ozali wapi na mobembo?",
    theMovement: "MOUVEMENTS",
    movementBadge: "Mouvements Ebandaki",
  },
  rw: {
    switchOn: "Fungura Ukwemera ⚡",
    watchVision: "Reba Video y'Inzozi",
    faithAlwaysOn: "⚡ Ukwemera. Butesha Igihe Cyose.",
    bibleVerse: '"Muri urumuri rw\'isi." — Matayo 5:14',
    heroSubtitle: "Jya hamwe n'abakiri bato 1M+ bihindura ukwemera kwabo guhishwa no kurwego rw'urumuri rubonetse — mu bihugu bya ECD.",
    heroTitle1: "Ukwemera Kwawe ni",
    heroTitle2: "Iswitche",
    heroTitle3: "Isi Iritegereje",
    watchTitle: "Reba",
    watchVisionText: "Inzozi",
    watchDesc: "Generation LightMode yazimiye ku kwizera gusa — ko isi ihinduka iyo abakiri bato bizeye bahagaritse guhisha ukwemera kwabo.",
    readMore: "Soma Byinshi kuri Inzozi →",
    lightSpreading: "Urumuri Rukwira",
    realImpact: "Impanuka nyayo. Abantu nyabo. Ukwemera kwa nyayo.",
    youthMobilized: "Urubyiruko rwa Guhamagarwa",
    peersReached: "Inshuti za Kugera",
    ecdNations: "Ibihugu bya ECD",
    glowGroups: "GlowGroups Zikora",
    whatIsLightMode: "LightMode ni",
    lightModeWord: "Iki?",
    learnMore: "Menya Byinshi →",
    takePledge: "Iga",
    pledgeWord: "Indahiro",
    signPledge: "Shyira Umukono ku Ndahiro ⚡",
    joinNow: "Injira Ubu ⚡",
    glowRank: "Urwego Rwawe rw'Urumuri",
    rankSubtitle: "Intambwe yose y'ukwemera ikutera imbere. Uri hehe mu rugendo?",
    theMovement: "IMBANZIRIZAMUCO",
    movementBadge: "Imbanzirizamuco Yatangiye",
  },
  ar: {
    switchOn: "أضئ إيمانك ⚡",
    watchVision: "شاهد فيديو الرؤية",
    faithAlwaysOn: "⚡ الإيمان. دائماً مضيء.",
    bibleVerse: '"أنتم نور العالم." — متى 5:14',
    heroSubtitle: "انضم إلى أكثر من مليون شاب مؤمن يحولون إيمانهم المخفي إلى نور مرئي — عبر أمم قسم أفريقيا الوسطى الشرقية.",
    heroTitle1: "إيمانك هو",
    heroTitle2: "المفتاح",
    heroTitle3: "الذي ينتظره العالم",
    watchTitle: "شاهد",
    watchVisionText: "الرؤية",
    watchDesc: "ولدت جيل لايت مود من إيمان بسيط — أن العالم يتغير عندما يتوقف الشباب المؤمن عن إخفاء إيمانهم.",
    readMore: "اقرأ المزيد عن الرؤية ←",
    lightSpreading: "النور ينتشر",
    realImpact: "تأثير حقيقي. أشخاص حقيقيون. إيمان حقيقي.",
    youthMobilized: "شباب سيُعبَّأ",
    peersReached: "أقران سيُوصَلون",
    ecdNations: "أمم ECD",
    glowGroups: "مجموعات توهج نشطة",
    whatIsLightMode: "ما هو",
    lightModeWord: "لايت مود؟",
    learnMore: "تعلم المزيد ←",
    takePledge: "أخذ",
    pledgeWord: "العهد",
    signPledge: "وقّع العهد ⚡",
    joinNow: "انضم الآن ⚡",
    glowRank: "رتبتك المضيئة",
    rankSubtitle: "كل خطوة إيمان ترفعك. أين أنت في الرحلة؟",
    theMovement: "الحركة",
    movementBadge: "الحركة بدأت",
  },
  am: {
    switchOn: "እምነትህን አብራ ⚡",
    watchVision: "የራዕይ ቪዲዮ ይመልከቱ",
    faithAlwaysOn: "⚡ እምነት። ሁሌም ያበራል።",
    bibleVerse: '"እናንተ የዓለም ብርሃን ናችሁ።" — ማቴዎስ 5:14',
    heroSubtitle: "ከ1M+ ወጣት አማኞች ጋር ተቀላቀሉ — ደብቀውት የነበረ እምነት ወደሚታይ ብርሃን እየቀየሩ።",
    heroTitle1: "እምነትህ ነው",
    heroTitle2: "ቁልፉ",
    heroTitle3: "ዓለም የሚጠብቀው",
    watchTitle: "ይመልከቱ",
    watchVisionText: "ራዕዩን",
    watchDesc: "Generation LightMode ከቀላል እምነት ተወለደ — ዓለም የሚለወጠው ወጣት አማኞች እምነታቸውን መደበቅ ሲያቆሙ ነው።",
    readMore: "ስለ ራዕዩ ተጨማሪ ያንብቡ →",
    lightSpreading: "ብርሃኑ ይሰራጫል",
    realImpact: "እውነተኛ ተፅዕኖ። እውነተኛ ሰዎች። እውነተኛ እምነት።",
    youthMobilized: "ወጣቶች ሊሰበሰቡ",
    peersReached: "እኩዮች ሊደረሱ",
    ecdNations: "የ ECD ሀገሮች",
    glowGroups: "ንቁ GlowGroups",
    whatIsLightMode: "LightMode ምንድን",
    lightModeWord: "ነው?",
    learnMore: "ተጨማሪ ይወቁ →",
    takePledge: "ቃለ",
    pledgeWord: "መሃላ ይምሉ",
    signPledge: "ቃለ መሃላ ይፈርሙ ⚡",
    joinNow: "አሁን ይቀላቀሉ ⚡",
    glowRank: "የእርስዎ ብርሃን ደረጃ",
    rankSubtitle: "እያንዳንዱ የእምነት እርምጃ ያሳድጋል። ጉዞው ላይ የት ነህ?",
    theMovement: "ንቅናቄ",
    movementBadge: "ንቅናቄው ተጀምሯል",
  },
  rn: {
    switchOn: "Tugura Ukwizera ⚡",
    watchVision: "Raba Videwo y'Ivyiyumviro",
    faithAlwaysOn: "⚡ Ukwizera. Butesha Igihe Cose.",
    bibleVerse: '"Muri urumuri rw\'isi." — Matayo 5:14',
    heroSubtitle: "Injira n'abarundi 1M+ bigisha ukwizera kwabo kwahishwe no kwerekana nk'urumuri.",
    heroTitle1: "Ukwizera Kwawe ni",
    heroTitle2: "Iswitche",
    heroTitle3: "Isi Yitegereza",
    watchTitle: "Raba",
    watchVisionText: "Ivyiyumviro",
    watchDesc: "Generation LightMode yazimiye ku kwizera gusa — ko isi ihinduka iyo abarundi bizeye bahagaritse guhisha ukwizera kwabo.",
    readMore: "Soma Vyinshi kuri Ivyiyumviro →",
    lightSpreading: "Urumuri Rukwira",
    realImpact: "Ingaruka nyayo. Abantu nyabo. Ukwizera kwa nyayo.",
    youthMobilized: "Urubyiruko rwa Guhamagarwa",
    peersReached: "Inshuti za Kugera",
    ecdNations: "Ibihugu bya ECD",
    glowGroups: "GlowGroups Zikora",
    whatIsLightMode: "LightMode ni",
    lightModeWord: "Iki?",
    learnMore: "Menya Vyinshi →",
    takePledge: "Iga",
    pledgeWord: "Indahiro",
    signPledge: "Shyira Umukono ku Ndahiro ⚡",
    joinNow: "Injira Ubu ⚡",
    glowRank: "Urwego Rwawe rw'Urumuri",
    rankSubtitle: "Intambwe yose y'ukwizera ikutera imbere. Uri hehe mu rugendo?",
    theMovement: "UMUTUMBA",
    movementBadge: "Umutumba Watanguye",
  },
  pt: {
    switchOn: "Liga a Tua Fé ⚡",
    watchVision: "Ver o Vídeo da Visão",
    faithAlwaysOn: "⚡ Fé. Sempre Ligada.",
    bibleVerse: '"Vós sois a luz do mundo." — Mateus 5:14',
    heroSubtitle: "Junte-se a mais de 1M de jovens crentes transformando a fé escondida em luz visível — nas nações da Divisão da África Centro-Oriental.",
    heroTitle1: "A Sua Fé É",
    heroTitle2: "O Interruptor",
    heroTitle3: "Que O Mundo Espera",
    watchTitle: "Ver a",
    watchVisionText: "Visão",
    watchDesc: "Generation LightMode nasceu de uma crença simples — que o mundo muda quando os jovens crentes param de esconder a sua fé.",
    readMore: "Leia Mais Sobre a Visão →",
    lightSpreading: "A Luz Está a Espalhar-se",
    realImpact: "Impacto real. Pessoas reais. Fé real.",
    youthMobilized: "Jovens a Mobilizar",
    peersReached: "Pares a Alcançar",
    ecdNations: "Nações da ECD",
    glowGroups: "GlowGroups Ativos",
    whatIsLightMode: "O que é",
    lightModeWord: "LightMode?",
    learnMore: "Saber Mais →",
    takePledge: "Fazer o",
    pledgeWord: "Juramento",
    signPledge: "Assinar o Juramento ⚡",
    joinNow: "Aderir Agora ⚡",
    glowRank: "O Seu Nível Glow",
    rankSubtitle: "Cada passo de fé faz-te subir. Onde estás na jornada?",
    theMovement: "O MOVIMENTO",
    movementBadge: "O Movimento Começou",
  },
  so: {
    switchOn: "Shid Rumaysadkaaga ⚡",
    watchVision: "Daawo Fiidiyaha Aragtida",
    faithAlwaysOn: "⚡ Rumaysad. Weligiis Shidan.",
    bibleVerse: '"Idinkaa ah iftiinka adduunka." — Matayos 5:14',
    heroSubtitle: "Ku biir 1M+ dhallinyaro xidid ah oo u bedelaya rumaystaha qarsoon nuur muuqda — dalalka Qaybta Bariga Afrika.",
    heroTitle1: "Rumaysadkaagu waa",
    heroTitle2: "Badhanka",
    heroTitle3: "Adduunku Sugayo",
    watchTitle: "Daawo",
    watchVisionText: "Aragtida",
    watchDesc: "Generation LightMode waxay ka dhasay rumayn fudud — in adduunku isbeddelo marka dhallinyaradda xididdada ah ay joojiso qarinta rumaysadkooda.",
    readMore: "Wax Badan ka Akhri Aragtida →",
    lightSpreading: "Iftiinku Faafaya",
    realImpact: "Saameyn dhab ah. Dad dhab ah. Rumaysad dhab ah.",
    youthMobilized: "Dhallinyarada la Mobilize gareynayo",
    peersReached: "Xididdada la Gaari doono",
    ecdNations: "Dalalka ECD",
    glowGroups: "GlowGroups Firfircoon",
    whatIsLightMode: "LightMode",
    lightModeWord: "maxay tahay?",
    learnMore: "Wax Badan Baro →",
    takePledge: "Qaado",
    pledgeWord: "Ballan-qaadka",
    signPledge: "Saxiix Ballan-qaadka ⚡",
    joinNow: "Ku Biir Hadda ⚡",
    glowRank: "Heerkaaga Iftiinka",
    rankSubtitle: "Tallaabo kasta oo xididdadeed ayaa kuu sarreeya. Xagee ayaad ku jirtaa safarka?",
    theMovement: "DHAQDHAQAAQA",
    movementBadge: "Dhaqdhaqaaqu Bilaabmay",
  },
  ti: {
    switchOn: "እምነትካ ኣብርህ ⚡",
    watchVision: "ናይ ራእይ ቪዲዮ ርአ",
    faithAlwaysOn: "⚡ እምነት። ኩሉ ግዜ ደሚቑ።",
    bibleVerse: '"ንስኻትኩም ናይ ዓለም ብርሃን ኢኹም።" — ማቴዎስ 5:14',
    heroSubtitle: "ምስ 1M+ ዘሎ ሓዊ እምነት ዘለዎ ወጻእቲ ተጸምበሩ።",
    heroTitle1: "እምነትካ",
    heroTitle2: "መፍትሒ",
    heroTitle3: "ዓለም ዘጽበዮ ዘሎ",
    watchTitle: "ርአ",
    watchVisionText: "ራእዩ",
    watchDesc: "Generation LightMode ካብ ቀሊል እምነት ተወሊዱ — ዓለም ዝቕየር ወጻእቲ እምነቶም ምሕባእ ምስ ኣቋረጹ ኢዩ።",
    readMore: "ብዛዕባ ራእይ ተወሳኺ ኣንብብ →",
    lightSpreading: "ብርሃን ይዝርጋሕ",
    realImpact: "ቀንዲ ሳዕቤን። ቀንዲ ሰባት። ቀንዲ እምነት።",
    youthMobilized: "ወጻእቲ ዝዋሃቡ",
    peersReached: "ብጾት ዝውሃቡ",
    ecdNations: "ሃገራት ECD",
    glowGroups: "ንቑሓት GlowGroups",
    whatIsLightMode: "LightMode እንታይ",
    lightModeWord: "ኢዩ?",
    learnMore: "ተወሳኺ ተምሃር →",
    takePledge: "ቃል",
    pledgeWord: "ኪዳን",
    signPledge: "ቃል ኪዳን ፈርም ⚡",
    joinNow: "ሕጂ ተጸምበር ⚡",
    glowRank: "ደረጃ ብርሃንካ",
    rankSubtitle: "ኩሉ ስጉምቲ እምነት የዕብየካ። ኣበይ ኢኻ ኣብ ጉዕዞ?",
    theMovement: "ምንቅስቓስ",
    movementBadge: "ምንቅስቓስ ጀሚሩ",
  },
  nus: {
    switchOn: "Cɔk Nhiam ⚡",
    watchVision: "Yiik Video de Yic",
    faithAlwaysOn: "⚡ Nhiam. Cɔk Kedec.",
    bibleVerse: '"Ee ɣo wec de piny." — Mat 5:14',
    heroSubtitle: "Lɔ kek 1M+ latde nhiamdun wek ɣo ca nhiam wec.",
    heroTitle1: "Nhamdu ee",
    heroTitle2: "Cɔk",
    heroTitle3: "Piny Kɔc La Tuany",
    watchTitle: "Yiik",
    watchVisionText: "Yic",
    watchDesc: "Generation LightMode rɔt ke nhiam — piny la gweth ke kɔc wec nhiam.",
    readMore: "Kɔc Bɛ Yic →",
    lightSpreading: "Wec Athɔɔ",
    realImpact: "Gweth. Kɔc. Nhiam.",
    youthMobilized: "Ruac de Cɔk",
    peersReached: "Kɔcden de Bɛ",
    ecdNations: "Wun ECD",
    glowGroups: "GlowGroups Kedec",
    whatIsLightMode: "LightMode",
    lightModeWord: "ee ŋo?",
    learnMore: "Nɔŋ Bɛ →",
    takePledge: "Cam",
    pledgeWord: "Tuany",
    signPledge: "Gɔr Tuany ⚡",
    joinNow: "Lɔ Ke Caa ⚡",
    glowRank: "Paan Wecdu",
    rankSubtitle: "Luak kedec la gweth. Ye ku ŋo?",
    theMovement: "NYUƆƆTH",
    movementBadge: "Nyuɔɔth Cuɔɔl",
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem("glm_language") || "en");

  const setLang = (code) => {
    setLangState(code);
    localStorage.setItem("glm_language", code);
  };

  useEffect(() => {
    const handler = (e) => setLangState(e.detail);
    window.addEventListener("languageChange", handler);
    return () => window.removeEventListener("languageChange", handler);
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] || translations.en }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}